fixtures:
  repositories:
    archive:
      repo: "https://github.com/voxpupuli/puppet-archive"
      ref: "v7.0.0"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "v9.1.0"
  symlinks:
    drupal: "#{source_dir}"
