HOSTS:
  debian-10-64:
    platform: debian-10-amd64
    hypervisor: docker
    image: debian:10
    docker_preserve_image: true
    docker_image_commands:
      - 'apt-get update && apt-get -y --no-install-recommends install curl wget git unzip php-cli php-xml'

CONFIG:
  type: aio
  log_level: info
  trace_limit: 500
